name: data_repository
description: Sensor data provider.

publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  equatable: ^2.0.5
  mock_sensor_data:
    path: ../mock_sensor_data
  